### ISSUE TITLE
packagist discoverable

### ISSUE THREAD

**Issue by meszarosrob** [gmazzap/Tela#1]
Hey,

do you plan to submit Tela to packagist?

Can't be loaded via composer right now.

> Could not find package giuseppe-mazzapica/tela at any version for your minimum-stability (stable).

**Comment by gmazzap** [comment]
@meszarosrob this package is highly experimental, and I don't know if I will make changes that break backward compatibily.

In fact, does not even exist a release (nor a git tag), so at the moment, I would not put this on packagist.

If you want to you use this package (at your own risk ;)) you can use `repository` settings in composer.json

like:

``` json
"repositories" : [
    {
        "type" : "vcs",
        "url"  : "https://github.com/Giuseppe-Mazzapica/Tela"
    }
]
```

then require the package as usual.

**Comment by meszarosrob** [comment]
Got it! Thank you for explanation.
